export default function buildShippingVariantStudioBindings({
  shippingVariants,
  activeShippingVariantIndex,
  getShippingReadiness,
  getVariantColor,
  getVariantColorLight,
  getShippingVariantSummary,
  activeShippingVariant,
  strategyGuidance,
  activeReadiness,
  shippingReadinessList,
  isActiveControlLike,
  shippingCurrentRates,
  shippingCurrentSetupLoading,
  shippingCurrentSetupError,
  shippingStudioEnhancementsEnabled,
  selectedStrategyChoice,
  shippingStrategyGroups,
  shippingStrategyChoices,
  isStrategyChoiceActive,
  activeShippingGuidedStep,
  selectedShippingCategory,
  selectedCategoryNeedsMethods,
  activeDeliveryMethodNames,
  activeSelectedMethodIds,
  activeConfiguredRates,
  shippingUiAdvancedOpen,
  selectedShippingCategoryLabel,
  thresholdAmount,
  percentOff,
  discountAmount,
  hasShippingBlocker,
  shippingBlockerMessage,
  shippingOperationResult,
  onRunShippingDiagnostics,
  setShippingVariantTabIndex,
  setShippingGuidedStep,
  setShippingCurrentSetupRefreshKey,
  handleShippingStrategyChoice,
  handleShippingCategorySelect,
  toggleActiveDeliveryMethodName,
  selectAllActiveDeliveryMethods,
  updateActiveDeliveryMethodNames,
  addReplacementRateForMethod,
  removeReplacementRateForMethod,
  renderGuidedShippingProgress,
  renderShippingOfferStep,
  renderShippingPrimaryFields,
  renderShippingBaselineField,
  renderShippingTargetingFields,
  renderGuidedShippingFooter,
}) {
  const activeVariantLabel =
    activeShippingVariant?.name || `Variant ${activeShippingVariantIndex + 1}`;

  return {
    state: {
      shippingVariants,
      activeShippingVariantIndex,
      getShippingReadiness,
      getVariantColor,
      getVariantColorLight,
      getShippingVariantSummary,
      activeVariantName: activeVariantLabel,
      strategyGuidance,
      activeReadiness,
      shippingReadinessList,
      editor: {
        isActiveControlLike,
        shippingCurrentRates,
        shippingCurrentSetupLoading,
        shippingCurrentSetupError,
        shippingStudioEnhancementsEnabled,
        selectedStrategyChoice,
        shippingStrategyGroups,
        shippingStrategyChoices,
        isStrategyChoiceActive,
        activeShippingGuidedStep,
        selectedShippingCategory,
        selectedCategoryNeedsMethods,
        activeDeliveryMethodNames,
        activeSelectedMethodIds,
        activeConfiguredRates,
        shippingUiAdvancedOpen,
        reviewPanelProps: {
          selectedShippingCategory,
          selectedShippingCategoryLabel,
          activeDeliveryMethodNames,
          activeConfiguredRates,
          thresholdAmount,
          percentOff,
          discountAmount,
          hasShippingBlocker,
          shippingBlockerMessage,
          shippingOperationResult,
          onRunShippingDiagnostics,
        },
      },
    },
    actions: {
      onSelectVariant: index => {
        setShippingVariantTabIndex(index);
        const variant = shippingVariants[index];
        const readiness = getShippingReadiness?.(variant?.config || {});
        if (readiness?.status === 'ready') {
          setShippingGuidedStep('review');
          return;
        }
        setShippingGuidedStep('type');
      },
      onRefreshControlBaseline: () => setShippingCurrentSetupRefreshKey(value => value + 1),
      handleShippingStrategyChoice,
      handleShippingCategorySelect,
      toggleActiveDeliveryMethodName,
      selectAllActiveDeliveryMethods,
      clearActiveDeliveryMethods: () =>
        updateActiveDeliveryMethodNames([], {
          clearScopeTargets: true,
        }),
      addReplacementRateForMethod,
      removeReplacementRateForMethod,
    },
    renderers: {
      renderGuidedShippingProgress,
      renderShippingOfferStep,
      renderShippingPrimaryFields,
      renderShippingBaselineField,
      renderShippingTargetingFields,
      renderGuidedShippingFooter,
    },
  };
}
