# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be18ce24d0354b555ea1a0b8af0bbcbe"
name = "RipperX"
application_url = "https://splitter.echologyx.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/api/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_online_store_pages,read_orders,read_products,write_products,read_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://splitter.echologyx.com/api/auth/callback" ]

[app_proxy]
url = "https://splitter.echologyx.com/api/proxy/script.js"
subpath = "ripx"
prefix = "apps"

[pos]
embedded = true
