# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
# Default Shopify CLI config (kept as production baseline).
# For explicit env targeting, use:
# - shopify.app.local.toml
# - shopify.app.production.toml

client_id = "475a569769b25edb8df85288e1be9637"
name = "RipperX"
application_url = "https://splitter.echologyx.com/home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://splitter.echologyx.com/api/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "https://splitter.echologyx.com/api/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,read_content,read_delivery_customizations,read_discounts,read_online_store_pages,read_orders,read_payment_customizations,read_products,read_shipping,write_cart_transforms,write_delivery_customizations,write_discounts,write_payment_customizations,write_products,write_shipping"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://splitter.echologyx.com/api/auth/callback" ]

[app_proxy]
url = "https://splitter.echologyx.com/api/proxy/script.js"
subpath = "ripx"
prefix = "apps"

[pos]
embedded = true
