import { createEmptyVisualEditorRule } from './visualEditorRuleHelpers';

export const DEFAULT_FORM_DATA = {
  name: '',
  description: '',
  type: 'price',
  target_type: '',
  target_id: '',
  pricePerProduct: false,
  goal: {
    type: 'conversion',
    metric: 'revenue',
    secondary: [],
    significance_level: 0.95,
    statistical_power: 0.8,
    conversion_window_days: 30,
    conversion_url: '',
    analysis_method: 'frequentist',
  },
  variants: [
    { name: 'Control', allocation: 50, config: {} },
    { name: 'Variant A', allocation: 50, config: {} },
  ],
  segments: {
    device: 'all',
    customer: 'all',
    countries: [],
    operating_system: 'all',
    excluded_product_ids: [],
    traffic_source: 'all',
    anti_flicker_mode: 'balanced',
    url_pattern: '',
    min_sessions: '',
    page_rules: [],
    device_rules: [],
    audience_rules: [],
    traffic_source_rules: [],
    traffic_ramp_percent: '',
    traffic_ramp_days: 7,
    js_targeting: { enabled: false, code: '' },
    visual_editor_rules: Array.from({ length: 5 }, () => createEmptyVisualEditorRule()),
    price_surface_mappings: [],
  },
  holdout_percent: 0,
  scheduled_start_at: '',
  scheduled_stop_at: '',
  auto_start: false,
  auto_stop: false,
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  guardrail_config: { enabled: false, minDropPercent: 10 },
};
