/**
 * Example checkout discount config — copy is generated by:
 *   npm run shopify:checkout-discount:sync-config
 * from repo root .env (APP_URL, RIPX_CHECKOUT_PRICE_SECRET).
 * The real ripxConfig.js is gitignored; do not commit production secrets.
 */
export const RIPX_PRICE_RESOLVE_BATCH_URL =
  'https://your-api.example.com/api/track/price-resolve-batch';
export const RIPX_SHIPPING_RESOLVE_BATCH_URL =
  'https://your-api.example.com/api/track/shipping-resolve-batch';

export const RIPX_CHECKOUT_PRICE_SECRET = '';

export const RIPX_CHECKOUT_PROBE_ALWAYS_DISCOUNT = false;
export const RIPX_CHECKOUT_PROBE_ATTRIBUTE_MATRIX = false;
